// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bomi.proto

// Protobuf Java Version: 4.26.1
package io.github.algomaster99.terminator.commons.fingerprint.protobuf;

public interface BomiOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:io.github.algomaster99.terminator.commons.fingerprint.protobuf.Bomi)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile classFile = 1;</code>
     */
    java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile> getClassFileList();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile classFile = 1;</code>
     */
    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile getClassFile(int index);
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile classFile = 1;</code>
     */
    int getClassFileCount();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile classFile = 1;</code>
     */
    java.util.List<? extends io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFileOrBuilder>
            getClassFileOrBuilderList();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile classFile = 1;</code>
     */
    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFileOrBuilder getClassFileOrBuilder(int index);
}
