// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bomi.proto

// Protobuf Java Version: 4.26.1
package io.github.algomaster99.terminator.commons.fingerprint.protobuf;

/**
 * Protobuf type {@code io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile}
 */
public final class ClassFile extends com.google.protobuf.GeneratedMessage
        implements
        // @@protoc_insertion_point(message_implements:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)
        ClassFileOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 26,
                /* patch= */ 1,
                /* suffix= */ "",
                ClassFile.class.getName());
    }
    // Use ClassFile.newBuilder() to construct.
    private ClassFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ClassFile() {
        className_ = "";
        attribute_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.class,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Builder.class);
    }

    public interface AttributeOrBuilder
            extends
            // @@protoc_insertion_point(interface_extends:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string hash = 1;</code>
         * @return Whether the hash field is set.
         */
        boolean hasHash();
        /**
         * <code>required string hash = 1;</code>
         * @return The hash.
         */
        java.lang.String getHash();
        /**
         * <code>required string hash = 1;</code>
         * @return The bytes for hash.
         */
        com.google.protobuf.ByteString getHashBytes();

        /**
         * <code>required string version = 3;</code>
         * @return Whether the version field is set.
         */
        boolean hasVersion();
        /**
         * <code>required string version = 3;</code>
         * @return The version.
         */
        java.lang.String getVersion();
        /**
         * <code>required string version = 3;</code>
         * @return The bytes for version.
         */
        com.google.protobuf.ByteString getVersionBytes();
    }
    /**
     * Protobuf type {@code io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute}
     */
    public static final class Attribute extends com.google.protobuf.GeneratedMessage
            implements
            // @@protoc_insertion_point(message_implements:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)
            AttributeOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 26,
                    /* patch= */ 1,
                    /* suffix= */ "",
                    Attribute.class.getName());
        }
        // Use Attribute.newBuilder() to construct.
        private Attribute(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Attribute() {
            hash_ = "";
            version_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                    .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_Attribute_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                    .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_Attribute_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.class,
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                                    .class);
        }

        private int bitField0_;
        public static final int HASH_FIELD_NUMBER = 1;

        @SuppressWarnings("serial")
        private volatile java.lang.Object hash_ = "";
        /**
         * <code>required string hash = 1;</code>
         * @return Whether the hash field is set.
         */
        @java.lang.Override
        public boolean hasHash() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string hash = 1;</code>
         * @return The hash.
         */
        @java.lang.Override
        public java.lang.String getHash() {
            java.lang.Object ref = hash_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    hash_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string hash = 1;</code>
         * @return The bytes for hash.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getHashBytes() {
            java.lang.Object ref = hash_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                hash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VERSION_FIELD_NUMBER = 3;

        @SuppressWarnings("serial")
        private volatile java.lang.Object version_ = "";
        /**
         * <code>required string version = 3;</code>
         * @return Whether the version field is set.
         */
        @java.lang.Override
        public boolean hasVersion() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string version = 3;</code>
         * @return The version.
         */
        @java.lang.Override
        public java.lang.String getVersion() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    version_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string version = 3;</code>
         * @return The bytes for version.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getVersionBytes() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                version_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasHash()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasVersion()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, hash_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, version_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, hash_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, version_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)) {
                return super.equals(obj);
            }
            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute other =
                    (io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute) obj;

            if (hasHash() != other.hasHash()) return false;
            if (hasHash()) {
                if (!getHash().equals(other.getHash())) return false;
            }
            if (hasVersion() != other.hasVersion()) return false;
            if (hasVersion()) {
                if (!getVersion().equals(other.getVersion())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasHash()) {
                hash = (37 * hash) + HASH_FIELD_NUMBER;
                hash = (53 * hash) + getHash().hashCode();
            }
            if (hasVersion()) {
                hash = (37 * hash) + VERSION_FIELD_NUMBER;
                hash = (53 * hash) + getVersion().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                parseDelimitedFrom(
                        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements
                // @@protoc_insertion_point(builder_implements:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                        .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_Attribute_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                        .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_Attribute_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                                        .class,
                                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                                        .Builder.class);
            }

            // Construct using
            // io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.newBuilder()
            private Builder() {}

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                hash_ = "";
                version_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                        .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_Attribute_descriptor;
            }

            @java.lang.Override
            public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                    getDefaultInstanceForType() {
                return io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                        .getDefaultInstance();
            }

            @java.lang.Override
            public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute build() {
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute result =
                        buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute buildPartial() {
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute result =
                        new io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(
                    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.hash_ = hash_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.version_ = version_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other
                        instanceof io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute) {
                    return mergeFrom(
                            (io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute other) {
                if (other
                        == io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                                .getDefaultInstance()) return this;
                if (other.hasHash()) {
                    hash_ = other.hash_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.hasVersion()) {
                    version_ = other.version_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasHash()) {
                    return false;
                }
                if (!hasVersion()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                hash_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 26: {
                                version_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 26
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object hash_ = "";
            /**
             * <code>required string hash = 1;</code>
             * @return Whether the hash field is set.
             */
            public boolean hasHash() {
                return ((bitField0_ & 0x00000001) != 0);
            }
            /**
             * <code>required string hash = 1;</code>
             * @return The hash.
             */
            public java.lang.String getHash() {
                java.lang.Object ref = hash_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        hash_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string hash = 1;</code>
             * @return The bytes for hash.
             */
            public com.google.protobuf.ByteString getHashBytes() {
                java.lang.Object ref = hash_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    hash_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string hash = 1;</code>
             * @param value The hash to set.
             * @return This builder for chaining.
             */
            public Builder setHash(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                hash_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>required string hash = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearHash() {
                hash_ = getDefaultInstance().getHash();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>required string hash = 1;</code>
             * @param value The bytes for hash to set.
             * @return This builder for chaining.
             */
            public Builder setHashBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                hash_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private java.lang.Object version_ = "";
            /**
             * <code>required string version = 3;</code>
             * @return Whether the version field is set.
             */
            public boolean hasVersion() {
                return ((bitField0_ & 0x00000002) != 0);
            }
            /**
             * <code>required string version = 3;</code>
             * @return The version.
             */
            public java.lang.String getVersion() {
                java.lang.Object ref = version_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        version_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string version = 3;</code>
             * @return The bytes for version.
             */
            public com.google.protobuf.ByteString getVersionBytes() {
                java.lang.Object ref = version_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    version_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string version = 3;</code>
             * @param value The version to set.
             * @return This builder for chaining.
             */
            public Builder setVersion(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                version_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }
            /**
             * <code>required string version = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearVersion() {
                version_ = getDefaultInstance().getVersion();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }
            /**
             * <code>required string version = 3;</code>
             * @param value The bytes for version to set.
             * @return This builder for chaining.
             */
            public Builder setVersionBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                version_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)
        }

        // @@protoc_insertion_point(class_scope:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute)
        private static final io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute();
        }

        public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Attribute> PARSER =
                new com.google.protobuf.AbstractParser<Attribute>() {
                    @java.lang.Override
                    public Attribute parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        Builder builder = newBuilder();
                        try {
                            builder.mergeFrom(input, extensionRegistry);
                        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                            throw e.setUnfinishedMessage(builder.buildPartial());
                        } catch (com.google.protobuf.UninitializedMessageException e) {
                            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                        } catch (java.io.IOException e) {
                            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                    .setUnfinishedMessage(builder.buildPartial());
                        }
                        return builder.buildPartial();
                    }
                };

        public static com.google.protobuf.Parser<Attribute> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Attribute> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }
    }

    private int bitField0_;
    public static final int CLASSNAME_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private volatile java.lang.Object className_ = "";
    /**
     * <code>required string className = 1;</code>
     * @return Whether the className field is set.
     */
    @java.lang.Override
    public boolean hasClassName() {
        return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string className = 1;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                className_ = s;
            }
            return s;
        }
    }
    /**
     * <code>required string className = 1;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            className_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ATTRIBUTE_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>
            attribute_;
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>
            getAttributeList() {
        return attribute_;
    }
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    @java.lang.Override
    public java.util.List<
                    ? extends
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder>
            getAttributeOrBuilderList() {
        return attribute_;
    }
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    @java.lang.Override
    public int getAttributeCount() {
        return attribute_.size();
    }
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    @java.lang.Override
    public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute getAttribute(int index) {
        return attribute_.get(index);
    }
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    @java.lang.Override
    public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder
            getAttributeOrBuilder(int index) {
        return attribute_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasClassName()) {
            memoizedIsInitialized = 0;
            return false;
        }
        for (int i = 0; i < getAttributeCount(); i++) {
            if (!getAttribute(i).isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, className_);
        }
        for (int i = 0; i < attribute_.size(); i++) {
            output.writeMessage(2, attribute_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, className_);
        }
        for (int i = 0; i < attribute_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, attribute_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)) {
            return super.equals(obj);
        }
        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile other =
                (io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile) obj;

        if (hasClassName() != other.hasClassName()) return false;
        if (hasClassName()) {
            if (!getClassName().equals(other.getClassName())) return false;
        }
        if (!getAttributeList().equals(other.getAttributeList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasClassName()) {
            hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
            hash = (53 * hash) + getClassName().hashCode();
        }
        if (getAttributeCount() > 0) {
            hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
            hash = (53 * hash) + getAttributeList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseDelimitedFrom(
            java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)
            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                    .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                    .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.class,
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Builder.class);
        }

        // Construct using io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.newBuilder()
        private Builder() {}

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            className_ = "";
            if (attributeBuilder_ == null) {
                attribute_ = java.util.Collections.emptyList();
            } else {
                attribute_ = null;
                attributeBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.BomiProto
                    .internal_static_io_github_algomaster99_terminator_commons_fingerprint_protobuf_ClassFile_descriptor;
        }

        @java.lang.Override
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile getDefaultInstanceForType() {
            return io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.getDefaultInstance();
        }

        @java.lang.Override
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile build() {
            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile buildPartial() {
            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile result =
                    new io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile result) {
            if (attributeBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    attribute_ = java.util.Collections.unmodifiableList(attribute_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.attribute_ = attribute_;
            } else {
                result.attribute_ = attributeBuilder_.build();
            }
        }

        private void buildPartial0(io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.className_ = className_;
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile) {
                return mergeFrom((io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile other) {
            if (other == io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.getDefaultInstance())
                return this;
            if (other.hasClassName()) {
                className_ = other.className_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (attributeBuilder_ == null) {
                if (!other.attribute_.isEmpty()) {
                    if (attribute_.isEmpty()) {
                        attribute_ = other.attribute_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureAttributeIsMutable();
                        attribute_.addAll(other.attribute_);
                    }
                    onChanged();
                }
            } else {
                if (!other.attribute_.isEmpty()) {
                    if (attributeBuilder_.isEmpty()) {
                        attributeBuilder_.dispose();
                        attributeBuilder_ = null;
                        attribute_ = other.attribute_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        attributeBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                ? getAttributeFieldBuilder()
                                : null;
                    } else {
                        attributeBuilder_.addAllMessages(other.attribute_);
                    }
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            if (!hasClassName()) {
                return false;
            }
            for (int i = 0; i < getAttributeCount(); i++) {
                if (!getAttribute(i).isInitialized()) {
                    return false;
                }
            }
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            className_ = input.readBytes();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute m =
                                    input.readMessage(
                                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile
                                                    .Attribute.parser(),
                                            extensionRegistry);
                            if (attributeBuilder_ == null) {
                                ensureAttributeIsMutable();
                                attribute_.add(m);
                            } else {
                                attributeBuilder_.addMessage(m);
                            }
                            break;
                        } // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object className_ = "";
        /**
         * <code>required string className = 1;</code>
         * @return Whether the className field is set.
         */
        public boolean hasClassName() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string className = 1;</code>
         * @return The className.
         */
        public java.lang.String getClassName() {
            java.lang.Object ref = className_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    className_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>required string className = 1;</code>
         * @return The bytes for className.
         */
        public com.google.protobuf.ByteString getClassNameBytes() {
            java.lang.Object ref = className_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                className_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>required string className = 1;</code>
         * @param value The className to set.
         * @return This builder for chaining.
         */
        public Builder setClassName(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            className_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>required string className = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearClassName() {
            className_ = getDefaultInstance().getClassName();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        /**
         * <code>required string className = 1;</code>
         * @param value The bytes for className to set.
         * @return This builder for chaining.
         */
        public Builder setClassNameBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            className_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>
                attribute_ = java.util.Collections.emptyList();

        private void ensureAttributeIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                attribute_ = new java.util.ArrayList<
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>(attribute_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder>
                attributeBuilder_;

        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>
                getAttributeList() {
            if (attributeBuilder_ == null) {
                return java.util.Collections.unmodifiableList(attribute_);
            } else {
                return attributeBuilder_.getMessageList();
            }
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public int getAttributeCount() {
            if (attributeBuilder_ == null) {
                return attribute_.size();
            } else {
                return attributeBuilder_.getCount();
            }
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute getAttribute(
                int index) {
            if (attributeBuilder_ == null) {
                return attribute_.get(index);
            } else {
                return attributeBuilder_.getMessage(index);
            }
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder setAttribute(
                int index, io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute value) {
            if (attributeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAttributeIsMutable();
                attribute_.set(index, value);
                onChanged();
            } else {
                attributeBuilder_.setMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder setAttribute(
                int index,
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                        builderForValue) {
            if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                attribute_.set(index, builderForValue.build());
                onChanged();
            } else {
                attributeBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder addAttribute(
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute value) {
            if (attributeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAttributeIsMutable();
                attribute_.add(value);
                onChanged();
            } else {
                attributeBuilder_.addMessage(value);
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder addAttribute(
                int index, io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute value) {
            if (attributeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAttributeIsMutable();
                attribute_.add(index, value);
                onChanged();
            } else {
                attributeBuilder_.addMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder addAttribute(
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                        builderForValue) {
            if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                attribute_.add(builderForValue.build());
                onChanged();
            } else {
                attributeBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder addAttribute(
                int index,
                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                        builderForValue) {
            if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                attribute_.add(index, builderForValue.build());
                onChanged();
            } else {
                attributeBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder addAllAttribute(
                java.lang.Iterable<
                                ? extends
                                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile
                                                .Attribute>
                        values) {
            if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, attribute_);
                onChanged();
            } else {
                attributeBuilder_.addAllMessages(values);
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder clearAttribute() {
            if (attributeBuilder_ == null) {
                attribute_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                attributeBuilder_.clear();
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public Builder removeAttribute(int index) {
            if (attributeBuilder_ == null) {
                ensureAttributeIsMutable();
                attribute_.remove(index);
                onChanged();
            } else {
                attributeBuilder_.remove(index);
            }
            return this;
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                getAttributeBuilder(int index) {
            return getAttributeFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder
                getAttributeOrBuilder(int index) {
            if (attributeBuilder_ == null) {
                return attribute_.get(index);
            } else {
                return attributeBuilder_.getMessageOrBuilder(index);
            }
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public java.util.List<
                        ? extends
                                io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile
                                        .AttributeOrBuilder>
                getAttributeOrBuilderList() {
            if (attributeBuilder_ != null) {
                return attributeBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(attribute_);
            }
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                addAttributeBuilder() {
            return getAttributeFieldBuilder()
                    .addBuilder(io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                            .getDefaultInstance());
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder
                addAttributeBuilder(int index) {
            return getAttributeFieldBuilder()
                    .addBuilder(
                            index,
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute
                                    .getDefaultInstance());
        }
        /**
         * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
         */
        public java.util.List<
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder>
                getAttributeBuilderList() {
            return getAttributeFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder>
                getAttributeFieldBuilder() {
            if (attributeBuilder_ == null) {
                attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute.Builder,
                        io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder>(
                        attribute_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
                attribute_ = null;
            }
            return attributeBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)
    }

    // @@protoc_insertion_point(class_scope:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)
    private static final io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile();
    }

    public static io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassFile> PARSER =
            new com.google.protobuf.AbstractParser<ClassFile>() {
                @java.lang.Override
                public ClassFile parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

    public static com.google.protobuf.Parser<ClassFile> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClassFile> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
