// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bomi.proto

// Protobuf Java Version: 4.26.1
package io.github.algomaster99.terminator.commons.fingerprint.protobuf;

public interface ClassFileOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string className = 1;</code>
     * @return Whether the className field is set.
     */
    boolean hasClassName();
    /**
     * <code>required string className = 1;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 1;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString getClassNameBytes();

    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    java.util.List<io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute>
            getAttributeList();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute getAttribute(int index);
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    int getAttributeCount();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    java.util.List<
                    ? extends
                            io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder>
            getAttributeOrBuilderList();
    /**
     * <code>repeated .io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.Attribute attribute = 2;</code>
     */
    io.github.algomaster99.terminator.commons.fingerprint.protobuf.ClassFile.AttributeOrBuilder getAttributeOrBuilder(
            int index);
}
